/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mpich_MPI */

#ifndef _Included_org_mpich_MPI
#define _Included_org_mpich_MPI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_mpich_MPI_MPI_COMM_NULL
#define org_mpich_MPI_MPI_COMM_NULL 67108864L
#undef org_mpich_MPI_BYTE
#define org_mpich_MPI_BYTE 1275068685L
#undef org_mpich_MPI_SHORT
#define org_mpich_MPI_SHORT 1275068931L
#undef org_mpich_MPI_INT
#define org_mpich_MPI_INT 1275069497L
#undef org_mpich_MPI_LONG
#define org_mpich_MPI_LONG 1275070522L
#undef org_mpich_MPI_FLOAT
#define org_mpich_MPI_FLOAT 1275069450L
#undef org_mpich_MPI_DOUBLE
#define org_mpich_MPI_DOUBLE 1275070475L
#undef org_mpich_MPI_BOOL_00415_00410N
#define org_mpich_MPI_BOOL_00415_00410N 1275068674L
#undef org_mpich_MPI_CHAR
#define org_mpich_MPI_CHAR 1275068932L
#undef org_mpich_MPI_BYTE_BUFFER
#define org_mpich_MPI_BYTE_BUFFER 8L
#undef org_mpich_MPI_SHORT_BUFFER
#define org_mpich_MPI_SHORT_BUFFER 7L
#undef org_mpich_MPI_INT_BUFFER
#define org_mpich_MPI_INT_BUFFER 6L
#undef org_mpich_MPI_LONG_BUFFER
#define org_mpich_MPI_LONG_BUFFER 5L
#undef org_mpich_MPI_FLOAT_BUFFER
#define org_mpich_MPI_FLOAT_BUFFER 4L
#undef org_mpich_MPI_DOUBLE_BUFFER
#define org_mpich_MPI_DOUBLE_BUFFER 3L
#undef org_mpich_MPI_BOOLEAN_BUFFER
#define org_mpich_MPI_BOOLEAN_BUFFER 2L
#undef org_mpich_MPI_CHAR_BUFFER
#define org_mpich_MPI_CHAR_BUFFER 1L
#undef org_mpich_MPI_OBJECT
#define org_mpich_MPI_OBJECT 9L
#undef org_mpich_MPI_MPI_MAX
#define org_mpich_MPI_MPI_MAX 1476395009L
#undef org_mpich_MPI_MPI_MIN
#define org_mpich_MPI_MPI_MIN 1476395010L
#undef org_mpich_MPI_MPI_SUM
#define org_mpich_MPI_MPI_SUM 1476395011L
#undef org_mpich_MPI_MPI_PROD
#define org_mpich_MPI_MPI_PROD 1476395012L
#undef org_mpich_MPI_MPI_LAND
#define org_mpich_MPI_MPI_LAND 1476395013L
#undef org_mpich_MPI_MPI_BAND
#define org_mpich_MPI_MPI_BAND 1476395014L
#undef org_mpich_MPI_MPI_LOR
#define org_mpich_MPI_MPI_LOR 1476395015L
#undef org_mpich_MPI_MPI_BOR
#define org_mpich_MPI_MPI_BOR 1476395016L
#undef org_mpich_MPI_MPI_LXOR
#define org_mpich_MPI_MPI_LXOR 1476395017L
#undef org_mpich_MPI_MPI_BXOR
#define org_mpich_MPI_MPI_BXOR 1476395018L
#undef org_mpich_MPI_MPI_MINLOC
#define org_mpich_MPI_MPI_MINLOC 1476395019L
#undef org_mpich_MPI_MPI_MAXLOC
#define org_mpich_MPI_MPI_MAXLOC 1476395020L
#undef org_mpich_MPI_MPI_REPLACE
#define org_mpich_MPI_MPI_REPLACE 1476395021L
#undef org_mpich_MPI_MPI_NO_OP
#define org_mpich_MPI_MPI_NO_OP 1476395022L
#undef org_mpich_MPI_MPI_MODE_RDONLY
#define org_mpich_MPI_MPI_MODE_RDONLY 2L
#undef org_mpich_MPI_MPI_MODE_RDWR
#define org_mpich_MPI_MPI_MODE_RDWR 8L
#undef org_mpich_MPI_MPI_MODE_WRONLY
#define org_mpich_MPI_MPI_MODE_WRONLY 4L
#undef org_mpich_MPI_MPI_MODE_CREATE
#define org_mpich_MPI_MPI_MODE_CREATE 1L
#undef org_mpich_MPI_MPI_MODE_EXCL
#define org_mpich_MPI_MPI_MODE_EXCL 64L
#undef org_mpich_MPI_MPI_MODE_DELETE_ON_CLOSE
#define org_mpich_MPI_MPI_MODE_DELETE_ON_CLOSE 16L
#undef org_mpich_MPI_MPI_MODE_UNIQUE_OPEN
#define org_mpich_MPI_MPI_MODE_UNIQUE_OPEN 32L
#undef org_mpich_MPI_MPI_MODE_APPEND
#define org_mpich_MPI_MPI_MODE_APPEND 128L
#undef org_mpich_MPI_MPI_MODE_SEQUENTIAL
#define org_mpich_MPI_MPI_MODE_SEQUENTIAL 256L
#undef org_mpich_MPI_MPI_UNDEFINED
#define org_mpich_MPI_MPI_UNDEFINED -32766L
#undef org_mpich_MPI_MPI_INFO_NULL
#define org_mpich_MPI_MPI_INFO_NULL 469762048L
#undef org_mpich_MPI_MPI_COMM_WORLD
#define org_mpich_MPI_MPI_COMM_WORLD 1140850688L
/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Init
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Init
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Finalize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Finalize
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Send
 * Signature: (Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Send
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Bsend
 * Signature: (Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Bsend
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ssend
 * Signature: (Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ssend
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Rsend
 * Signature: (Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Rsend
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Recv
 * Signature: (Ljava/lang/Object;IIIILorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Recv
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Isend
 * Signature: (Ljava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Isend
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ibsend
 * Signature: (Ljava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ibsend
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Issend
 * Signature: (Ljava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Issend
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Irsend
 * Signature: (Ljava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Irsend
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Irecv
 * Signature: (Ljava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Irecv
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Get_count
 * Signature: (Lorg/mpich/MPI_Status;I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Get_1count
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Buffer_attach
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Buffer_1attach
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Buffer_detach
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Buffer_1detach
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Wait
 * Signature: (Lorg/mpich/MPI_Request;Lorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Wait
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Test
 * Signature: (Lorg/mpich/MPI_Request;Lorg/mpich/MPI_Status;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mpich_MPI_MPI_1Test
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Waitany
 * Signature: ([Lorg/mpich/MPI_Request;Lorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Waitany
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Testany
 * Signature: ([Lorg/mpich/MPI_Request;Lorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Testany
  (JNIEnv *, jclass, jobjectArray, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Waitall
 * Signature: ([Lorg/mpich/MPI_Request;[Lorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Waitall
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Testall
 * Signature: ([Lorg/mpich/MPI_Request;[Lorg/mpich/MPI_Status;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mpich_MPI_MPI_1Testall
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Waitsome
 * Signature: ([Lorg/mpich/MPI_Request;[I[Lorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Waitsome
  (JNIEnv *, jclass, jobjectArray, jintArray, jobjectArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Testsome
 * Signature: ([Lorg/mpich/MPI_Request;[I[Lorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Testsome
  (JNIEnv *, jclass, jobjectArray, jintArray, jobjectArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Request_get_status
 * Signature: (Lorg/mpich/MPI_Request;Lorg/mpich/MPI_Status;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mpich_MPI_MPI_1Request_1get_1status
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Request_free
 * Signature: (Lorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Request_1free
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Probe
 * Signature: (IIILorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Probe
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Iprobe
 * Signature: (IIILorg/mpich/MPI_Status;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mpich_MPI_MPI_1Iprobe
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Mprobe
 * Signature: (IIILorg/mpich/MPI_Message;Lorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Mprobe
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Improbe
 * Signature: (IIILorg/mpich/MPI_Message;Lorg/mpich/MPI_Status;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mpich_MPI_MPI_1Improbe
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Mrecv
 * Signature: (Ljava/lang/Object;ILorg/mpich/MPI_Message;Lorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Mrecv
  (JNIEnv *, jclass, jobject, jint, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Imrecv
 * Signature: (Ljava/lang/Object;ILorg/mpich/MPI_Message;Lorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Imrecv
  (JNIEnv *, jclass, jobject, jint, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Cancel
 * Signature: (Lorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Cancel
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Test_cancelled
 * Signature: (Lorg/mpich/MPI_Status;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mpich_MPI_MPI_1Test_1cancelled
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Send_init
 * Signature: (Ljava/nio/ByteBuffer;IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Send_1init
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Bsend_init
 * Signature: (Ljava/nio/ByteBuffer;IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Bsend_1init
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ssend_init
 * Signature: (Ljava/nio/ByteBuffer;IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ssend_1init
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Rsend_init
 * Signature: (Ljava/nio/ByteBuffer;IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Rsend_1init
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Recv_init
 * Signature: (Ljava/nio/ByteBuffer;IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Recv_1init
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Start
 * Signature: (Lorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Start
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Startall
 * Signature: ([Lorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Startall
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Sendrecv
 * Signature: (Ljava/lang/Object;IIILjava/lang/Object;IIIILorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Sendrecv
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Sendrecv_replace
 * Signature: (Ljava/lang/Object;IIIIIILorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Sendrecv_1replace
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Barrier
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Barrier
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ibarrier
 * Signature: (ILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ibarrier
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Bcast
 * Signature: (Ljava/lang/Object;III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Bcast
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ibcast
 * Signature: (Ljava/lang/Object;IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ibcast
  (JNIEnv *, jclass, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Scatter
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Scatter
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Gather
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Gather
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Scatterv
 * Signature: (Ljava/lang/Object;[I[IILjava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Scatterv
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Gatherv
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;[I[IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Gatherv
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jintArray, jintArray, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Iscatterv
 * Signature: (Ljava/lang/Object;[I[IILjava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Iscatterv
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Igatherv
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;[I[IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Igatherv
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jintArray, jintArray, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_2DScatter
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_12DScatter
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_2DGather
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_12DGather
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Iscatter
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Iscatter
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Igather
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Igather
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_I2DScatter
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1I2DScatter
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_I2DGather
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1I2DGather
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Allgather
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Allgather
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Allgatherv
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;[I[III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Allgatherv
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Iallgatherv
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;[I[IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Iallgatherv
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jintArray, jintArray, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Iallgather
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Iallgather
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Alltoall
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Alltoall
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ialltoall
 * Signature: (Ljava/lang/Object;IILjava/lang/Object;IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ialltoall
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Alltoallv
 * Signature: (Ljava/lang/Object;[I[IILjava/lang/Object;[I[III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Alltoallv
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jint, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ialltoallv
 * Signature: (Ljava/lang/Object;[I[IILjava/lang/Object;[I[IIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ialltoallv
  (JNIEnv *, jclass, jobject, jintArray, jintArray, jint, jobject, jintArray, jintArray, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Reduce
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Reduce
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ireduce
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ireduce
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Allreduce
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Allreduce
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Iallreduce
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Iallreduce
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Reduce_scatter
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;[IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Reduce_1scatter
  (JNIEnv *, jclass, jobject, jobject, jintArray, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ireduce_scatter
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;[IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ireduce_1scatter
  (JNIEnv *, jclass, jobject, jobject, jintArray, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Reduce_scatter_block
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Reduce_1scatter_1block
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Ireduce_scatter_block
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Ireduce_1scatter_1block
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Scan
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Scan
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Iscan
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Iscan
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Exscan
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Exscan
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Iexscan
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Iexscan
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_rank
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1rank
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_translate_ranks
 * Signature: (II[II[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1translate_1ranks
  (JNIEnv *, jclass, jint, jint, jintArray, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_compare
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1compare
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_union
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1union
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_intersection
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1intersection
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_difference
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1difference
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_incl
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1incl
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_excl
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1excl
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_range_incl
 * Signature: (II[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1range_1incl
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_range_excl
 * Signature: (II[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1range_1excl
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Group_free
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Group_1free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_rank
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1rank
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_compare
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1compare
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_dup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1dup
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_dup_with_info
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1dup_1with_1info
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_idup
 * Signature: (ILorg/mpich/MPI_Request;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1idup
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_create
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1create
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_create_group
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1create_1group
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_split
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1split
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_split_type
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1split_1type
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_free
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_set_info
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1set_1info
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_get_info
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1get_1info
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_group
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1group
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_test_inter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1test_1inter
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_remote_size
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1remote_1size
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_remote_group
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1remote_1group
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Intercomm_create
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Intercomm_1create
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Intercomm_merge
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Intercomm_1merge
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_set_name
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1set_1name
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Com_get_name
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mpich_MPI_MPI_1Com_1get_1name
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Cart_create
 * Signature: (II[I[II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Cart_1create
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Dims_create
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Dims_1create
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Graph_create
 * Signature: (II[I[II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Graph_1create
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Dist_graph_create_adjacent
 * Signature: (II[I[II[I[III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Dist_1graph_1create_1adjacent
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jint, jintArray, jintArray, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Dist_graph_create
 * Signature: (II[I[I[I[III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Dist_1graph_1create
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Test_info
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Test_1info
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Graphdims_get
 * Signature: (ILorg/mpich/MPI_Integer_ref;Lorg/mpich/MPI_Integer_ref;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Graphdims_1get
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Graph_get
 * Signature: (III[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Graph_1get
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Cartdim_get
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Cartdim_1get
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Cart_get
 * Signature: (II[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Cart_1get
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Cart_rank
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Cart_1rank
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Cart_coords
 * Signature: (III[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Cart_1coords
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Graph_neighbors_count
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Graph_1neighbors_1count
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Graph_neighbors
 * Signature: (III[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Graph_1neighbors
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Dist_graph_neighbors_count
 * Signature: (ILorg/mpich/MPI_Integer_ref;Lorg/mpich/MPI_Integer_ref;Lorg/mpich/MPI_Integer_ref;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Dist_1graph_1neighbors_1count
  (JNIEnv *, jclass, jint, jobject, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Dist_graph_neighbors
 * Signature: (II[I[II[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Dist_1graph_1neighbors
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jint, jintArray, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Cart_shift
 * Signature: (IIILorg/mpich/MPI_Integer_ref;Lorg/mpich/MPI_Integer_ref;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Cart_1shift
  (JNIEnv *, jclass, jint, jint, jint, jobject, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Cart_sub
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Cart_1sub
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Cart_map
 * Signature: (II[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Cart_1map
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Graph_map
 * Signature: (II[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Graph_1map
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Get_version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Get_1version
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Get_library_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mpich_MPI_MPI_1Get_1library_1version
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Get_process_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mpich_MPI_MPI_1Get_1process_1name
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Wtime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_mpich_MPI_MPI_1Wtime
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Wtick
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_mpich_MPI_MPI_1Wtick
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Initialized
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Initialized
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Abort
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Abort
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Finalized
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Finalized
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Info_create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Info_1create
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Info_set
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Info_1set
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Info_delete
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Info_1delete
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Info_get
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mpich_MPI_MPI_1Info_1get
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Info_get_valuelen
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Info_1get_1valuelen
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Info_get_nthkey
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mpich_MPI_MPI_1Info_1get_1nthkey
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Info_dup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Info_1dup
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Info_free
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Info_1free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_spawn
 * Signature: (Ljava/lang/String;[Ljava/lang/String;IIII[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1spawn
  (JNIEnv *, jclass, jstring, jobjectArray, jint, jint, jint, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_get_parent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1get_1parent
  (JNIEnv *, jclass);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_spawn_multiple
 * Signature: ([Ljava/lang/String;[[Ljava/lang/String;[I[III[I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1spawn_1multiple
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jintArray, jintArray, jint, jint, jintArray);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_disconnect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1disconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_join
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1join
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Open_port
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mpich_MPI_MPI_1Open_1port
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Close_port
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Close_1port
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_accept
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1accept
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Comm_connect
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Comm_1connect
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Publish_name
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Publish_1name
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Unpublich_name
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Unpublich_1name
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Lookup_name
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mpich_MPI_MPI_1Lookup_1name
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_create
 * Signature: (Lorg/mpich/MPI_Win_buffer;III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1create
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_allocate
 * Signature: (IIILorg/mpich/MPI_Win_buffer;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1allocate
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_allocate_shared
 * Signature: (IIILorg/mpich/MPI_Win_buffer;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1allocate_1shared
  (JNIEnv *, jclass, jint, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_shared_query
 * Signature: (IILorg/mpich/MPI_Win_buffer;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1shared_1query
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_create_dynamic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1create_1dynamic
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_attach
 * Signature: (ILorg/mpich/MPI_Win_buffer;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1attach
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_detach
 * Signature: (ILorg/mpich/MPI_Win_buffer;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1detach
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_free
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1free
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_get_attr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1get_1attr
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_get_group
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1get_1group
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_set_info
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1set_1info
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_get_info
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1get_1info
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_fence
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1fence
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_start
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1start
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_complete
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1complete
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_post
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1post
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_wait
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1wait
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_test
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mpich_MPI_MPI_1Win_1test
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_lock
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1lock
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_lock_all
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1lock_1all
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_unlock
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1unlock
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_unlock_all
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1unlock_1all
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_flush
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1flush
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_flush_all
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1flush_1all
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_flush_local
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1flush_1local
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_fluch_local_all
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1fluch_1local_1all
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Win_sync
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Win_1sync
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Put
 * Signature: (Lorg/mpich/MPI_Win_buffer;IIIJIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Put
  (JNIEnv *, jclass, jobject, jint, jint, jint, jlong, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Get
 * Signature: (Lorg/mpich/MPI_Win_buffer;IIIJIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Get
  (JNIEnv *, jclass, jobject, jint, jint, jint, jlong, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Accumulate
 * Signature: (Lorg/mpich/MPI_Win_buffer;IIIJIIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Accumulate
  (JNIEnv *, jclass, jobject, jint, jint, jint, jlong, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Get_accumulate
 * Signature: (Lorg/mpich/MPI_Win_buffer;IILjava/lang/Object;IIIJIIII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Get_1accumulate
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jint, jint, jint, jlong, jint, jint, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_Fetch_and_op
 * Signature: (Lorg/mpich/MPI_Win_buffer;Ljava/lang/Object;IIJII)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1Fetch_1and_1op
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jlong, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_open
 * Signature: (ILjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_org_mpich_MPI_MPI_1File_1open
  (JNIEnv *, jclass, jint, jstring, jint, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_delete
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1delete
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_set_size
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1set_1size
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_preallocate
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1preallocate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_get_group
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1get_1group
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_get_amode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1get_1amode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_set_info
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1set_1info
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_get_info
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1get_1info
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_set_view
 * Signature: (JJIILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1set_1view
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jstring, jint);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_get_view_disp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_mpich_MPI_MPI_1File_1get_1view_1disp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_get_view_etyp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1get_1view_1etyp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_get_view_filetype
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1get_1view_1filetype
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_get_view_datarep
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mpich_MPI_MPI_1File_1get_1view_1datarep
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_set_atomicity
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1set_1atomicity
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_read_at
 * Signature: (JJLjava/lang/Object;IILorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1read_1at
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_read_at_all
 * Signature: (JJLjava/lang/Object;IILorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1read_1at_1all
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_write_at
 * Signature: (JJLjava/lang/Object;IILorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1write_1at
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint, jobject);

/*
 * Class:     org_mpich_MPI
 * Method:    MPI_File_write_at_all
 * Signature: (JJLjava/lang/Object;IILorg/mpich/MPI_Status;)I
 */
JNIEXPORT jint JNICALL Java_org_mpich_MPI_MPI_1File_1write_1at_1all
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
