/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_op_Op */

#ifndef _Included_mpi_op_Op
#define _Included_mpi_op_Op
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpi_op_Op
 * Method:    _create
 * Signature: (Ljava/lang/Object;ZJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_op_Op__1create
  (JNIEnv *, jclass, jobject, jboolean, jlong);

/*
 * Class:     mpi_op_Op
 * Method:    _free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mpi_op_Op__1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
