/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_MPI */

#ifndef _Included_mpi_MPI
#define _Included_mpi_MPI
#ifdef __cplusplus
extern "C" {
#endif
#undef mpi_MPI_IDENT
#define mpi_MPI_IDENT 0L
#undef mpi_MPI_CONGRUENT
#define mpi_MPI_CONGRUENT 1L
#undef mpi_MPI_SIMILAR
#define mpi_MPI_SIMILAR 2L
#undef mpi_MPI_UNEQUAL
#define mpi_MPI_UNEQUAL 3L
#undef mpi_MPI_UNDEFINED
#define mpi_MPI_UNDEFINED -32766L
#undef mpi_MPI_TAG_UB
#define mpi_MPI_TAG_UB 1681915905L
#undef mpi_MPI_HOST
#define mpi_MPI_HOST 1681915907L
#undef mpi_MPI_IO
#define mpi_MPI_IO 1681915909L
#undef mpi_MPI_WTIME_IS_GLOBAL
#define mpi_MPI_WTIME_IS_GLOBAL 1681915911L
#undef mpi_MPI_UNIVERSE_SIZE
#define mpi_MPI_UNIVERSE_SIZE 1681915913L
#undef mpi_MPI_LASTUSEDCODE
#define mpi_MPI_LASTUSEDCODE 1681915915L
#undef mpi_MPI_APPNUM
#define mpi_MPI_APPNUM 1681915917L
#undef mpi_MPI_WIN_BASE
#define mpi_MPI_WIN_BASE 1711276033L
#undef mpi_MPI_WIN_SIZE
#define mpi_MPI_WIN_SIZE 1711276035L
#undef mpi_MPI_WIN_DISP_UNIT
#define mpi_MPI_WIN_DISP_UNIT 1711276037L
#undef mpi_MPI_WIN_CREATE_FLAVOR
#define mpi_MPI_WIN_CREATE_FLAVOR 1711276039L
#undef mpi_MPI_WIN_MODEL
#define mpi_MPI_WIN_MODEL 1711276041L
#undef mpi_MPI_ORDER_C
#define mpi_MPI_ORDER_C 56L
#undef mpi_MPI_ORDER_FORTRAN
#define mpi_MPI_ORDER_FORTRAN 57L
#undef mpi_MPI_DISTRIBUTE_BLOCK
#define mpi_MPI_DISTRIBUTE_BLOCK 121L
#undef mpi_MPI_DISTRIBUTE_CYCLIC
#define mpi_MPI_DISTRIBUTE_CYCLIC 122L
#undef mpi_MPI_DISTRIBUTE_NONE
#define mpi_MPI_DISTRIBUTE_NONE 123L
#undef mpi_MPI_DISTRIBUTE_DFLT_DARG
#define mpi_MPI_DISTRIBUTE_DFLT_DARG -49767L
#undef mpi_MPI_GRAPH
#define mpi_MPI_GRAPH 1L
#undef mpi_MPI_CART
#define mpi_MPI_CART 2L
#undef mpi_MPI_DIST_GRAPH
#define mpi_MPI_DIST_GRAPH 3L
#undef mpi_MPI_PROC_NULL
#define mpi_MPI_PROC_NULL -1L
#undef mpi_MPI_ANY_SOURCE
#define mpi_MPI_ANY_SOURCE -2L
#undef mpi_MPI_ROOT
#define mpi_MPI_ROOT -3L
#undef mpi_MPI_ANY_TAG
#define mpi_MPI_ANY_TAG -1L
#undef mpi_MPI_LIB_VERSION
#define mpi_MPI_LIB_VERSION 3L
#undef mpi_MPI_LIB_SUBVERSION
#define mpi_MPI_LIB_SUBVERSION 1L
#undef mpi_MPI_VERSION
#define mpi_MPI_VERSION 0L
#undef mpi_MPI_SUBVERSION
#define mpi_MPI_SUBVERSION 1L
#undef mpi_MPI_MODE_NOCHECK
#define mpi_MPI_MODE_NOCHECK 1024L
#undef mpi_MPI_MODE_NOSTORE
#define mpi_MPI_MODE_NOSTORE 2048L
#undef mpi_MPI_MODE_NOPUT
#define mpi_MPI_MODE_NOPUT 4096L
#undef mpi_MPI_MODE_NOPRECEDE
#define mpi_MPI_MODE_NOPRECEDE 8192L
#undef mpi_MPI_MODE_NOSUCCEED
#define mpi_MPI_MODE_NOSUCCEED 16384L
#undef mpi_MPI_LOCK_EXCLUSIVE
#define mpi_MPI_LOCK_EXCLUSIVE 234L
#undef mpi_MPI_LOCK_SHARED
#define mpi_MPI_LOCK_SHARED 235L
#undef mpi_MPI_COMM_TYPE_SHARED
#define mpi_MPI_COMM_TYPE_SHARED 1L
#undef mpi_MPI_MODE_RDONLY
#define mpi_MPI_MODE_RDONLY 2L
#undef mpi_MPI_MODE_RDWR
#define mpi_MPI_MODE_RDWR 8L
#undef mpi_MPI_MODE_WRONLY
#define mpi_MPI_MODE_WRONLY 4L
#undef mpi_MPI_MODE_CREATE
#define mpi_MPI_MODE_CREATE 1L
#undef mpi_MPI_MODE_EXCL
#define mpi_MPI_MODE_EXCL 64L
#undef mpi_MPI_MODE_DELETE_ON_CLOSE
#define mpi_MPI_MODE_DELETE_ON_CLOSE 16L
#undef mpi_MPI_MODE_UNIQUE_OPEN
#define mpi_MPI_MODE_UNIQUE_OPEN 32L
#undef mpi_MPI_MODE_APPEND
#define mpi_MPI_MODE_APPEND 128L
#undef mpi_MPI_MODE_SEQUENTIAL
#define mpi_MPI_MODE_SEQUENTIAL 256L
#undef mpi_MPI_SEEK_SET
#define mpi_MPI_SEEK_SET 600L
#undef mpi_MPI_SEEK_CUR
#define mpi_MPI_SEEK_CUR 602L
#undef mpi_MPI_SEEK_END
#define mpi_MPI_SEEK_END 604L
#undef mpi_MPI_THREAD_SINGLE
#define mpi_MPI_THREAD_SINGLE 0L
#undef mpi_MPI_THREAD_FUNNELED
#define mpi_MPI_THREAD_FUNNELED 1L
#undef mpi_MPI_THREAD_SERIALIZED
#define mpi_MPI_THREAD_SERIALIZED 2L
#undef mpi_MPI_THREAD_MULTIPLE
#define mpi_MPI_THREAD_MULTIPLE 3L
/*
 * Class:     mpi_MPI
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mpi_MPI_initNative
  (JNIEnv *, jclass);

/*
 * Class:     mpi_MPI
 * Method:    _init
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mpi_MPI__1init
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     mpi_MPI
 * Method:    _init_thread
 * Signature: ([Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_mpi_MPI__1init_1thread
  (JNIEnv *, jclass, jobjectArray, jint);

/*
 * Class:     mpi_MPI
 * Method:    _finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mpi_MPI__1finalize
  (JNIEnv *, jclass);

/*
 * Class:     mpi_MPI
 * Method:    _buffer_attach
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_mpi_MPI__1buffer_1attach
  (JNIEnv *, jclass, jobject);

/*
 * Class:     mpi_MPI
 * Method:    _buffer_detach
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_mpi_MPI__1buffer_1detach
  (JNIEnv *, jclass, jobject);

/*
 * Class:     mpi_MPI
 * Method:    _dims_create
 * Signature: (III[I)V
 */
JNIEXPORT void JNICALL Java_mpi_MPI__1dims_1create
  (JNIEnv *, jclass, jint, jint, jint, jintArray);

/*
 * Class:     mpi_MPI
 * Method:    _processor_name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mpi_MPI__1processor_1name
  (JNIEnv *, jclass);

/*
 * Class:     mpi_MPI
 * Method:    _wtime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_mpi_MPI__1wtime
  (JNIEnv *, jclass);

/*
 * Class:     mpi_MPI
 * Method:    _wtick
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_mpi_MPI__1wtick
  (JNIEnv *, jclass);

/*
 * Class:     mpi_MPI
 * Method:    _isInitialized
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_mpi_MPI__1isInitialized
  (JNIEnv *, jclass);

/*
 * Class:     mpi_MPI
 * Method:    _parent
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mpi_MPI__1parent
  (JNIEnv *, jclass);

/*
 * Class:     mpi_MPI
 * Method:    _open_port
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mpi_MPI__1open_1port
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_MPI
 * Method:    _close_port
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mpi_MPI__1close_1port
  (JNIEnv *, jclass, jstring);

/*
 * Class:     mpi_MPI
 * Method:    _publish_name
 * Signature: (Ljava/lang/String;JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mpi_MPI__1publish_1name
  (JNIEnv *, jclass, jstring, jlong, jstring);

/*
 * Class:     mpi_MPI
 * Method:    _unpublish_name
 * Signature: (Ljava/lang/String;JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mpi_MPI__1unpublish_1name
  (JNIEnv *, jclass, jstring, jlong, jstring);

/*
 * Class:     mpi_MPI
 * Method:    _lookup_name
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mpi_MPI__1lookup_1name
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     mpi_MPI
 * Method:    _file_delete
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_mpi_MPI__1file_1delete
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
