/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_Intercomm */

#ifndef _Included_mpi_Intercomm
#define _Included_mpi_Intercomm
#ifdef __cplusplus
extern "C" {
#endif
#undef mpi_Intercomm_null_handler
#define mpi_Intercomm_null_handler 67108864LL
/*
 * Class:     mpi_Intercomm
 * Method:    _test
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_mpi_Intercomm__1test
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_Intercomm
 * Method:    _remote_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mpi_Intercomm__1remote_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_Intercomm
 * Method:    _remote_group
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intercomm__1remote_1group
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_Intercomm
 * Method:    _intercomm_create
 * Signature: (JIJII)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intercomm__1intercomm_1create
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint);

/*
 * Class:     mpi_Intercomm
 * Method:    _merge
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intercomm__1merge
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     mpi_Intercomm
 * Method:    _disconnect
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intercomm__1disconnect
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
