/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_datatype_Subarray */

#ifndef _Included_mpi_datatype_Subarray
#define _Included_mpi_datatype_Subarray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpi_datatype_Subarray
 * Method:    _create_subarray
 * Signature: (I[I[I[IIJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_datatype_Subarray__1create_1subarray
  (JNIEnv *, jclass, jint, jintArray, jintArray, jintArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
