/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_Intracomm */

#ifndef _Included_mpi_Intracomm
#define _Included_mpi_Intracomm
#ifdef __cplusplus
extern "C" {
#endif
#undef mpi_Intracomm_null_handler
#define mpi_Intracomm_null_handler 67108864LL
/*
 * Class:     mpi_Intracomm
 * Method:    _create_group
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1create_1group
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     mpi_Intracomm
 * Method:    _create
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1create
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _split
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1split
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     mpi_Intracomm
 * Method:    _split_type
 * Signature: (JIIJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1split_1type
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _spawn
 * Signature: (Ljava/lang/String;[Ljava/lang/String;IJIJII[I)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1spawn
  (JNIEnv *, jclass, jstring, jobjectArray, jint, jlong, jint, jlong, jint, jint, jintArray);

/*
 * Class:     mpi_Intracomm
 * Method:    _accept
 * Signature: (Ljava/lang/String;JIJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1accept
  (JNIEnv *, jclass, jstring, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _connect
 * Signature: (Ljava/lang/String;JIJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1connect
  (JNIEnv *, jclass, jstring, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _cart_create
 * Signature: (JII[II[IZ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1cart_1create
  (JNIEnv *, jclass, jlong, jint, jint, jintArray, jint, jintArray, jboolean);

/*
 * Class:     mpi_Intracomm
 * Method:    _graph_create
 * Signature: (JII[II[IZ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1graph_1create
  (JNIEnv *, jclass, jlong, jint, jint, jintArray, jint, jintArray, jboolean);

/*
 * Class:     mpi_Intracomm
 * Method:    _topo_test
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mpi_Intracomm__1topo_1test
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _dist_graph_create
 * Signature: (JII[II[II[II[IJZ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1dist_1graph_1create
  (JNIEnv *, jclass, jlong, jint, jint, jintArray, jint, jintArray, jint, jintArray, jint, jintArray, jlong, jboolean);

/*
 * Class:     mpi_Intracomm
 * Method:    _bcast
 * Signature: (Ljava/lang/Object;IIJIJ)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1bcast
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _ibcast
 * Signature: (Ljava/lang/Object;IIJIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_Intracomm__1ibcast
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _scatter
 * Signature: (Ljava/lang/Object;IIJLjava/lang/Object;IIJIJ)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1scatter
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jobject, jint, jint, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _iscatter
 * Signature: (Ljava/lang/Object;IIJLjava/lang/Object;IIJIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_Intracomm__1iscatter
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jobject, jint, jint, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _gather
 * Signature: (Ljava/lang/Object;IIJLjava/lang/Object;IIJIJ)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1gather
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jobject, jint, jint, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _igather
 * Signature: (Ljava/lang/Object;IIJLjava/lang/Object;IIJIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_Intracomm__1igather
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jobject, jint, jint, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _allgather
 * Signature: (Ljava/lang/Object;IIJLjava/lang/Object;IIJJ)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1allgather
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jobject, jint, jint, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _iallgather
 * Signature: (Ljava/lang/Object;IIJLjava/lang/Object;IIJJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_Intracomm__1iallgather
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jobject, jint, jint, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _alltoall
 * Signature: (Ljava/lang/Object;IIJLjava/lang/Object;IIJJ)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1alltoall
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jobject, jint, jint, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _ialltoall
 * Signature: (Ljava/lang/Object;IIJLjava/lang/Object;IIJJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_Intracomm__1ialltoall
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jobject, jint, jint, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _reduce
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIJJIJ)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1reduce
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jlong, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _ireduce
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIJJIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_Intracomm__1ireduce
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jlong, jlong, jint, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _allreduce
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIJJJ)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1allreduce
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _iallreduce
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIJJJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_Intracomm__1iallreduce
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _scan
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIJJJ)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1scan
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _iscan
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIJJJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_Intracomm__1iscan
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _exscan
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIJJJ)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1exscan
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _iexscan
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;IIIJJJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_Intracomm__1iexscan
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jlong, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _win_create
 * Signature: (Ljava/nio/ByteBuffer;IJJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1win_1create
  (JNIEnv *, jclass, jobject, jint, jlong, jlong);

/*
 * Class:     mpi_Intracomm
 * Method:    _allocate
 * Signature: (JIJJLmpi/Win/Win_allocate_ret;)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1allocate
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jobject);

/*
 * Class:     mpi_Intracomm
 * Method:    _allocate_shared
 * Signature: (JIJJLmpi/Win/Win_allocate_ret;)V
 */
JNIEXPORT void JNICALL Java_mpi_Intracomm__1allocate_1shared
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jobject);

/*
 * Class:     mpi_Intracomm
 * Method:    _file_open
 * Signature: (JLjava/lang/String;IJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Intracomm__1file_1open
  (JNIEnv *, jclass, jlong, jstring, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
