/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_Message */

#ifndef _Included_mpi_Message
#define _Included_mpi_Message
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpi_Message
 * Method:    _mrecv
 * Signature: (Ljava/lang/Object;IIJJLmpi/Status;)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Message__1mrecv
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jlong, jobject);

/*
 * Class:     mpi_Message
 * Method:    _imrecv
 * Signature: (Ljava/lang/Object;IIJJLmpi/Request;)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Message__1imrecv
  (JNIEnv *, jclass, jobject, jint, jint, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
