/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_Group */

#ifndef _Included_mpi_Group
#define _Included_mpi_Group
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpi_Group
 * Method:    _size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mpi_Group__1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_Group
 * Method:    _rank
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mpi_Group__1rank
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_Group
 * Method:    _compare
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_mpi_Group__1compare
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mpi_Group
 * Method:    _free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mpi_Group__1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_Group
 * Method:    _incl
 * Signature: (JII[I)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Group__1incl
  (JNIEnv *, jclass, jlong, jint, jint, jintArray);

/*
 * Class:     mpi_Group
 * Method:    _excl
 * Signature: (JII[I)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Group__1excl
  (JNIEnv *, jclass, jlong, jint, jint, jintArray);

/*
 * Class:     mpi_Group
 * Method:    _difference
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Group__1difference
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mpi_Group
 * Method:    _intersection
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Group__1intersection
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mpi_Group
 * Method:    _union
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Group__1union
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mpi_Group
 * Method:    _translate_ranks
 * Signature: (JII[IJI[I)V
 */
JNIEXPORT void JNICALL Java_mpi_Group__1translate_1ranks
  (JNIEnv *, jclass, jlong, jint, jint, jintArray, jlong, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
