/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_Graph */

#ifndef _Included_mpi_Graph
#define _Included_mpi_Graph
#ifdef __cplusplus
extern "C" {
#endif
#undef mpi_Graph_null_handler
#define mpi_Graph_null_handler 67108864LL
/*
 * Class:     mpi_Graph
 * Method:    _graph_get
 * Signature: (JIIII[I[I)V
 */
JNIEXPORT void JNICALL Java_mpi_Graph__1graph_1get
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     mpi_Graph
 * Method:    _get_graphdims
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_mpi_Graph__1get_1graphdims
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     mpi_Graph
 * Method:    _neighbors
 * Signature: (JIII[I)V
 */
JNIEXPORT void JNICALL Java_mpi_Graph__1neighbors
  (JNIEnv *, jclass, jlong, jint, jint, jint, jintArray);

/*
 * Class:     mpi_Graph
 * Method:    _neighbors_count
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_mpi_Graph__1neighbors_1count
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
