/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_datatype_Datatype */

#ifndef _Included_mpi_datatype_Datatype
#define _Included_mpi_datatype_Datatype
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpi_datatype_Datatype
 * Method:    _commit
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_mpi_datatype_Datatype__1commit__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     mpi_datatype_Datatype
 * Method:    _commit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mpi_datatype_Datatype__1commit__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_datatype_Datatype
 * Method:    _type_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mpi_datatype_Datatype__1type_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
