/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_Cart */

#ifndef _Included_mpi_Cart
#define _Included_mpi_Cart
#ifdef __cplusplus
extern "C" {
#endif
#undef mpi_Cart_null_handler
#define mpi_Cart_null_handler 67108864LL
/*
 * Class:     mpi_Cart
 * Method:    _cart_coords
 * Signature: (JIII[I)V
 */
JNIEXPORT void JNICALL Java_mpi_Cart__1cart_1coords
  (JNIEnv *, jclass, jlong, jint, jint, jint, jintArray);

/*
 * Class:     mpi_Cart
 * Method:    _cart_rank
 * Signature: (JII[I)I
 */
JNIEXPORT jint JNICALL Java_mpi_Cart__1cart_1rank
  (JNIEnv *, jclass, jlong, jint, jint, jintArray);

/*
 * Class:     mpi_Cart
 * Method:    _cart_get
 * Signature: (JII[II[II[I)V
 */
JNIEXPORT void JNICALL Java_mpi_Cart__1cart_1get
  (JNIEnv *, jclass, jlong, jint, jint, jintArray, jint, jintArray, jint, jintArray);

/*
 * Class:     mpi_Cart
 * Method:    _shift
 * Signature: (JIIZ)I
 */
JNIEXPORT jint JNICALL Java_mpi_Cart__1shift
  (JNIEnv *, jclass, jlong, jint, jint, jboolean);

/*
 * Class:     mpi_Cart
 * Method:    _sub
 * Signature: (JII[I)J
 */
JNIEXPORT jlong JNICALL Java_mpi_Cart__1sub
  (JNIEnv *, jclass, jlong, jint, jint, jintArray);

/*
 * Class:     mpi_Cart
 * Method:    _dims
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mpi_Cart__1dims
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
