/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_File */

#ifndef _Included_mpi_File
#define _Included_mpi_File
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpi_File
 * Method:    _amode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mpi_File__1amode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_File
 * Method:    _atomicity
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1atomicity__JZ
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     mpi_File
 * Method:    _atomicity
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_mpi_File__1atomicity__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_File
 * Method:    _get_group
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mpi_File__1get_1group
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_File
 * Method:    _info
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mpi_File__1info
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_File
 * Method:    _get_position
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mpi_File__1get_1position
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_File
 * Method:    _get_position_shared
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mpi_File__1get_1position_1shared
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_File
 * Method:    _set_size
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1set_1size
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mpi_File
 * Method:    _get_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mpi_File__1get_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_File
 * Method:    _set_view
 * Signature: (JJJJLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1set_1view
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jstring, jlong);

/*
 * Class:     mpi_File
 * Method:    _preallocate
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1preallocate
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mpi_File
 * Method:    _seek
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1seek
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     mpi_File
 * Method:    _seek_shared
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1seek_1shared
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     mpi_File
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mpi_File
 * Method:    _write
 * Signature: (JLjava/lang/Object;IIJLmpi/Status;)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1write
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong, jobject);

/*
 * Class:     mpi_File
 * Method:    _write_at
 * Signature: (JJLjava/lang/Object;IIJLmpi/Status;)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1write_1at
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint, jlong, jobject);

/*
 * Class:     mpi_File
 * Method:    _read
 * Signature: (JLjava/lang/Object;IIJLmpi/Status;)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1read
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong, jobject);

/*
 * Class:     mpi_File
 * Method:    _read_at
 * Signature: (JJLjava/lang/Object;IIJLmpi/Status;)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1read_1at
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint, jlong, jobject);

/*
 * Class:     mpi_File
 * Method:    _write_shared
 * Signature: (JLjava/lang/Object;IIJLmpi/Status;)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1write_1shared
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong, jobject);

/*
 * Class:     mpi_File
 * Method:    _read_shared
 * Signature: (JLjava/lang/Object;IIJLmpi/Status;)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1read_1shared
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong, jobject);

/*
 * Class:     mpi_File
 * Method:    _write_all
 * Signature: (JLjava/lang/Object;IIJLmpi/Status;)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1write_1all
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong, jobject);

/*
 * Class:     mpi_File
 * Method:    _read_all
 * Signature: (JLjava/lang/Object;IIJLmpi/Status;)V
 */
JNIEXPORT void JNICALL Java_mpi_File__1read_1all
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong, jobject);

/*
 * Class:     mpi_File
 * Method:    _iwrite
 * Signature: (JLjava/lang/Object;IIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_File__1iwrite
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong);

/*
 * Class:     mpi_File
 * Method:    _iread
 * Signature: (JLjava/lang/Object;IIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_File__1iread
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong);

/*
 * Class:     mpi_File
 * Method:    _iwrite_shared
 * Signature: (JLjava/lang/Object;IIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_File__1iwrite_1shared
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong);

/*
 * Class:     mpi_File
 * Method:    _iread_shared
 * Signature: (JLjava/lang/Object;IIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_File__1iread_1shared
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jlong);

/*
 * Class:     mpi_File
 * Method:    _iwrite_at
 * Signature: (JJLjava/lang/Object;IIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_File__1iwrite_1at
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint, jlong);

/*
 * Class:     mpi_File
 * Method:    _iread_at
 * Signature: (JJLjava/lang/Object;IIJ)Lmpi/Request;
 */
JNIEXPORT jobject JNICALL Java_mpi_File__1iread_1at
  (JNIEnv *, jclass, jlong, jlong, jobject, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
